spring:
  profiles.active: dev
  application:
    name: Movie Booking System
  
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_booking_system
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update 
logging:
  level:
    org.springframework.web: INFO
    com.efmfm.notification: INFO
    org.hibernate: ERROR
  file: E:\\home\\logs\\application.log
  
server:
  port: 8079
  
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/movie_booking_system
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org.springframework.web: INFO
    com.efmfm.notification: INFO
    org.hibernate: ERROR
  file: /home/ubuntu/logs/notification.log
  
server:
  port: 8078
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/movie_booking_system
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      
logging:
  level:
    org.springframework.web: INFO
    com.efmfm.notification: INFO
    org.hibernate: ERROR
  file: /home/ubuntu/logs/notification.log
  
server:
  port: 8078
